### ISSUE TITLE
Build multi-architecture images to support Arm

### ISSUE THREAD

**Issue by dalehumby** [byrnedo/docker-alpine-curl#13]
Running 
`docker run --rm byrnedo/alpine-curl https://www.google.com`
on a Raspberry Pi 4B running latest Raspbery Pi OS gives error:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Running `docker image inspect byrnedo/alpine-curl` shows me that `"Architecture": "amd64"`

However, pulling and building the Dockerfile locally works as expected.

I suspect this is because there is no Arm image (Although I am relatively this so I may be incorrect.)

Please could you build Arm images? (See https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

Thanks

**Comment by byrnedo** [comment]
@dalehumby someone is interested in doing and arm image in PR, hopefully that'll get you up and running

**Comment by byrnedo** [comment]
Should be up on docker hub now.
