### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [byrnedo/docker-alpine-curl#14]
Hi Team,

I am trying to use the docker-alpine-curl image on the arm64 platform but it seems it is not available for it.

I tried to build it using the command **docker build -t docker-alpine-curl**  . on both amd64 and arm64 platforms and the image is building successfully for them.

I have used Travis-CI to build and push the image for both platforms.

Please check [here](https://github.com/odidev/docker-alpine-curl/commit/3b8f6828c41517aacda56a3bfbc6c07087a9c8fe) for the changes done in Travis to build and push the image.

Dockerhub Link - https://hub.docker.com/repository/docker/odidev/docker-alpine-curl

It will be very helpful if arm64 image is available. If interested, I will raise a PR.

**Comment by byrnedo** [comment]
Hi @odidev,
Sure, sounds good, raise a pr!

**Comment by byrnedo** [comment]
@odidev I guess I need to conf the travis build for this now myself in the travis ui?

**Comment by prabhat181998** [comment]
May I know when you are planning on releasing an ARM64 image?

**Comment by odidev** [comment]
May I know when you are planning on releasing an ARM64 image?

**Comment by byrnedo** [comment]
See my question above

**Comment by odidev** [comment]
Yes, you need to configure Travis-ci in order to publish the image.

Steps to setup Travis-ci -

1) Login into [travis-ci.com](https://travis-ci.com/)  and then activate travis-ci for your repository. For any doubts, Please refer [here](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github)

2) Add DOCKER_USERNAME and DOCKER_PASSWORD as the environment variables in Travis-CI. You can refer this[ link](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings)

3) Then create a new tag in Github and then Travis-CI will be automatically triggered.

**Comment by byrnedo** [comment]
@odidev Image up on docker hub now.
