### ISSUE TITLE
Tag docker image

### ISSUE THREAD

**Issue by palmerabollo** [byrnedo/docker-alpine-curl#3]
Is it possible to give the Docker images in [Docker Hub](https://hub.docker.com/r/byrnedo/alpine-curl/) a tag?

**Comment by byrnedo** [comment]
Sure, I'll throw something up.

**Comment by byrnedo** [comment]
Do you need the previous images to be tagged or is it enough to just tag a new one?

**Comment by palmerabollo** [comment]
A new one is enough. Thank you, Donal.

**Comment by byrnedo** [comment]
There's now a 0.1.3 and 0.1 (for all 0.1.x) tag up there now, enjoy!

**Comment by palmerabollo** [comment]
Thanks!

**Comment by byrnedo** [comment]
No problem, thanks for raising, should have been done from the start.
