### ISSUE TITLE
Repository Links

### ISSUE THREAD

**Issue by ktk** [byrnedo/docker-alpine-curl#7]
I'm not sure if you are using Repository Links for this image. From the Dockerhub description:

> Link your Automated Build to another Docker Hub repository, and when that repository is updated, it will automatically trigger a rebuild of this Automated Build.

In case you are not using it, it would be great if you could enable that in `Build Settings->Repository Links`, simply add `alpine` in there. That will make sure that we always have the latest image.

**Comment by byrnedo** [comment]
Sounds good, I'll add that!

**Comment by byrnedo** [comment]
Done!
